"""Initial schema for foods, meals, and meal items

Revision ID: 23ae96902881
Revises: 
Create Date: 2026-10-07 21:31:41.041199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ae96902881'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('local_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('sugar', sa.Float(), nullable=False),
    sa.Column('sodium', sa.Float(), nullable=False),
    sa.Column('is_indian_dish', sa.Boolean(), nullable=True),
    sa.Column('uncertainty_pct', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_category'), 'food_items', ['category'], unique=False)
    op.create_index(op.f('ix_food_items_id'), 'food_items', ['id'], unique=False)
    op.create_index(op.f('ix_food_items_is_indian_dish'), 'food_items', ['is_indian_dish'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein', sa.Float(), nullable=False),
    sa.Column('total_carbohydrates', sa.Float(), nullable=False),
    sa.Column('total_fat', sa.Float(), nullable=False),
    sa.Column('total_fiber', sa.Float(), nullable=False),
    sa.Column('uncertainty_calories', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_status'), 'meals', ['status'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=120), nullable=False),
    sa.Column('serving_count', sa.Float(), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('uncertainty_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_status'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_is_indian_dish'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_id'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_category'), table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
